site_name: Example Docs

theme:
  name: readthedocs

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            filters: null

nav:
  - index.md
